version: '3.4'

services:
  romanel.evaluation.api:
    image: ${DOCKER_REGISTRY-}romanelevaluationapi
    build:
      context: .
      dockerfile: Romanel.Evaluation.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ClienteDb;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data: